package modelo;
// Generated 09-12-2014 10:50:59 PM by Hibernate Tools 4.3.1



/**
 * Diaslibres generated by hbm2java
 */
public class Diaslibres  implements java.io.Serializable {


     private String idpers;
     private String dialibre;

    public Diaslibres() {
    }

    public Diaslibres(String idpers, String dialibre) {
       this.idpers = idpers;
       this.dialibre = dialibre;
    }
   
    public String getIdpers() {
        return this.idpers;
    }
    
    public void setIdpers(String idpers) {
        this.idpers = idpers;
    }
    public String getDialibre() {
        return this.dialibre;
    }
    
    public void setDialibre(String dialibre) {
        this.dialibre = dialibre;
    }




}


