package modelo;
// Generated 09-12-2014 10:50:59 PM by Hibernate Tools 4.3.1



/**
 * Empleado generated by hbm2java
 */
public class Empleado  implements java.io.Serializable {


     private String rut;
     private String nombre;
     private String apellido;
     private String estadocivil;
     private String sexo;
     private String fechanac;
     private String domicilio;
     private String fono;
     private String ciudad;
     private String region;
     private String comuna;
     private String pais;
     private String correo;

    public Empleado() {
    }

    public Empleado(String rut, String nombre, String apellido, String estadocivil, String sexo, String fechanac, String domicilio, String fono, String ciudad, String region, String comuna, String pais, String correo) {
       this.rut = rut;
       this.nombre = nombre;
       this.apellido = apellido;
       this.estadocivil = estadocivil;
       this.sexo = sexo;
       this.fechanac = fechanac;
       this.domicilio = domicilio;
       this.fono = fono;
       this.ciudad = ciudad;
       this.region = region;
       this.comuna = comuna;
       this.pais = pais;
       this.correo = correo;
    }
   
    public String getRut() {
        return this.rut;
    }
    
    public void setRut(String rut) {
        this.rut = rut;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getEstadocivil() {
        return this.estadocivil;
    }
    
    public void setEstadocivil(String estadocivil) {
        this.estadocivil = estadocivil;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public String getFechanac() {
        return this.fechanac;
    }
    
    public void setFechanac(String fechanac) {
        this.fechanac = fechanac;
    }
    public String getDomicilio() {
        return this.domicilio;
    }
    
    public void setDomicilio(String domicilio) {
        this.domicilio = domicilio;
    }
    public String getFono() {
        return this.fono;
    }
    
    public void setFono(String fono) {
        this.fono = fono;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    public String getRegion() {
        return this.region;
    }
    
    public void setRegion(String region) {
        this.region = region;
    }
    public String getComuna() {
        return this.comuna;
    }
    
    public void setComuna(String comuna) {
        this.comuna = comuna;
    }
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }




}


