package modelo;
// Generated 09-12-2014 10:50:59 PM by Hibernate Tools 4.3.1



/**
 * Infolaboral generated by hbm2java
 */
public class Infolaboral  implements java.io.Serializable {


     private String idpers;
     private String labor;
     private int hrssemanales;
     private String inicontrato;
     private String fincontrato;
     private String sueldobas;
     private String hrsextra;
     private String tipojornada;
     private String prevision;
     private String afp;
     private String mutual;
     private String lvlestudios;
     private String profesion;

    public Infolaboral() {
    }

    public Infolaboral(String idpers, String labor, int hrssemanales, String inicontrato, String fincontrato, String sueldobas, String hrsextra, String tipojornada, String prevision, String afp, String mutual, String lvlestudios, String profesion) {
       this.idpers = idpers;
       this.labor = labor;
       this.hrssemanales = hrssemanales;
       this.inicontrato = inicontrato;
       this.fincontrato = fincontrato;
       this.sueldobas = sueldobas;
       this.hrsextra = hrsextra;
       this.tipojornada = tipojornada;
       this.prevision = prevision;
       this.afp = afp;
       this.mutual = mutual;
       this.lvlestudios = lvlestudios;
       this.profesion = profesion;
    }
   
    public String getIdpers() {
        return this.idpers;
    }
    
    public void setIdpers(String idpers) {
        this.idpers = idpers;
    }
    public String getLabor() {
        return this.labor;
    }
    
    public void setLabor(String labor) {
        this.labor = labor;
    }
    public int getHrssemanales() {
        return this.hrssemanales;
    }
    
    public void setHrssemanales(int hrssemanales) {
        this.hrssemanales = hrssemanales;
    }
    public String getInicontrato() {
        return this.inicontrato;
    }
    
    public void setInicontrato(String inicontrato) {
        this.inicontrato = inicontrato;
    }
    public String getFincontrato() {
        return this.fincontrato;
    }
    
    public void setFincontrato(String fincontrato) {
        this.fincontrato = fincontrato;
    }
    public String getSueldobas() {
        return this.sueldobas;
    }
    
    public void setSueldobas(String sueldobas) {
        this.sueldobas = sueldobas;
    }
    public String getHrsextra() {
        return this.hrsextra;
    }
    
    public void setHrsextra(String hrsextra) {
        this.hrsextra = hrsextra;
    }
    public String getTipojornada() {
        return this.tipojornada;
    }
    
    public void setTipojornada(String tipojornada) {
        this.tipojornada = tipojornada;
    }
    public String getPrevision() {
        return this.prevision;
    }
    
    public void setPrevision(String prevision) {
        this.prevision = prevision;
    }
    public String getAfp() {
        return this.afp;
    }
    
    public void setAfp(String afp) {
        this.afp = afp;
    }
    public String getMutual() {
        return this.mutual;
    }
    
    public void setMutual(String mutual) {
        this.mutual = mutual;
    }
    public String getLvlestudios() {
        return this.lvlestudios;
    }
    
    public void setLvlestudios(String lvlestudios) {
        this.lvlestudios = lvlestudios;
    }
    public String getProfesion() {
        return this.profesion;
    }
    
    public void setProfesion(String profesion) {
        this.profesion = profesion;
    }




}


