package modelo;
// Generated 09-12-2014 10:50:59 PM by Hibernate Tools 4.3.1



/**
 * Turnostrabajador generated by hbm2java
 */
public class Turnostrabajador  implements java.io.Serializable {


     private TurnostrabajadorId id;
     private String comentarios;

    public Turnostrabajador() {
    }

    public Turnostrabajador(TurnostrabajadorId id, String comentarios) {
       this.id = id;
       this.comentarios = comentarios;
    }
   
    public TurnostrabajadorId getId() {
        return this.id;
    }
    
    public void setId(TurnostrabajadorId id) {
        this.id = id;
    }
    public String getComentarios() {
        return this.comentarios;
    }
    
    public void setComentarios(String comentarios) {
        this.comentarios = comentarios;
    }




}


