package modelo;
// Generated 09-12-2014 10:50:59 PM by Hibernate Tools 4.3.1



/**
 * TurnostrabajadorId generated by hbm2java
 */
public class TurnostrabajadorId  implements java.io.Serializable {


     private String idpers;
     private int idturno;

    public TurnostrabajadorId() {
    }

    public TurnostrabajadorId(String idpers, int idturno) {
       this.idpers = idpers;
       this.idturno = idturno;
    }
   
    public String getIdpers() {
        return this.idpers;
    }
    
    public void setIdpers(String idpers) {
        this.idpers = idpers;
    }
    public int getIdturno() {
        return this.idturno;
    }
    
    public void setIdturno(int idturno) {
        this.idturno = idturno;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TurnostrabajadorId) ) return false;
		 TurnostrabajadorId castOther = ( TurnostrabajadorId ) other; 
         
		 return ( (this.getIdpers()==castOther.getIdpers()) || ( this.getIdpers()!=null && castOther.getIdpers()!=null && this.getIdpers().equals(castOther.getIdpers()) ) )
 && (this.getIdturno()==castOther.getIdturno());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdpers() == null ? 0 : this.getIdpers().hashCode() );
         result = 37 * result + this.getIdturno();
         return result;
   }   


}


